-- 03_seed.sql
USE lab_emprestimos;

-- Limpa tabelas de itens (opcional em ambientes de teste)
TRUNCATE TABLE notebook;
TRUNCATE TABLE celular;
TRUNCATE TABLE camera;

-- NOTEBOOKS (1..35)
INSERT INTO notebook (codigo, patrimonio, status, manutencao)
SELECT n, CONCAT('NB', LPAD(n,4,'0')), 'disponivel', 0
FROM (
  SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
  UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
  UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15
  UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20
  UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25
  UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30
  UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35
) x;

-- CELULARES (1..16)
INSERT INTO celular (codigo, patrimonio, status, manutencao)
SELECT n, CONCAT('CE', LPAD(n,4,'0')), 'disponivel', 0
FROM (
  SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8
  UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12
  UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16
) x;

-- CÂMERAS (1..2)
INSERT INTO camera (codigo, patrimonio, status, manutencao)
SELECT n, CONCAT('CA', LPAD(n,4,'0')), 'disponivel', 0
FROM (
  SELECT 1 n UNION ALL SELECT 2
) x;
