-- 03_seed.sql
USE lab_emprestimos;

-- Limpa tabelas de itens (opcional em ambientes de teste)
TRUNCATE TABLE notebook;
TRUNCATE TABLE celular;
TRUNCATE TABLE camera;

-- NOTEBOOKS (1..15)
INSERT INTO notebook (codigo, patrimonio, status, manutencao)
SELECT n, CONCAT('NB', LPAD(n,4,'0')), 'disponivel', 0
FROM (SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
      UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
      UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15) x;

-- CELULARES (1..10)
INSERT INTO celular (codigo, patrimonio, status, manutencao)
SELECT n, CONCAT('CE', LPAD(n,4,'0')), 'disponivel', 0
FROM (SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
      UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) x;

-- CÂMERAS (1..6)
INSERT INTO camera (codigo, patrimonio, status, manutencao)
SELECT n, CONCAT('CA', LPAD(n,4,'0')), 'disponivel', 0
FROM (SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6) x;
